#!/usr/bin/env bash
# Очищаем экран
clear
# Подгружаем переменнные
#source <(curl -s http://repo.ald.minfin.ru/repo/sos/foo)
# или указываем вручную
#------------------------------------------#
repo_proto="https"
repo_name="dl.astralinux.ru"
set_repo="true"
#------------------------------------------#
# Выполняем проверку прав суперпользователя
if [ "$USER" != "root" ]; then
    whiptail --title "Проверка прав sudo" --msgbox "Для выполнения скрипта нужны права sudo, запустите скрипт с правами суперпользователя" 10 60
    #echo "Для выполнения скрипта нужны права sudo, запустите скрипт с правами суперпользователя"
#else
    exit 1
fi
####################################################################
#                                                                  #
#     Ввод переменных                                              #
#                                                                  #
####################################################################
# Введите имя репозитория
#read -e -p "Введите имя репозитория " -i "$repo_name"  repo_name
repo_name=$(whiptail --title "Установка клиента ALDPro" --inputbox "\nВведите имя репозитория: " 10 60 $repo_name 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
    echo "  "
    else
    echo "Вы выбрали отмену."
    exit 1
    fi
# Выберете протокол репозитория
#read -e -p "Введите протокол репозитория " -i "$repo_proto"  repo_proto
OPTION=$(whiptail --title "Установка клиента ALDPro" --menu "\nВыберите протокол репозитория: " 10 60 3 \
    "1" "https" \
    "2" "http" \
    "3" "ftp" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
    #echo "Вы выбрали:" $OPTION
    # "1" "https" \
        if [ $OPTION == 1 ]; then
            #echo "https"
            repo_proto="https"
    # "2" "http" \
        elif [ $OPTION == 2 ]; then
            #echo "https"
            repo_proto="http"
    # "3" "ftp" \
        elif [ $OPTION == 3 ]; then
            #echo "ftp"
            repo_proto="ftp"
        fi
    else
        echo "Вы нажали отмену."
        exit 1
    fi
####################################################################
#                                                                  #
#     Вывод переменных                                             #
#                                                                  #
####################################################################
echo -e "\n"
echo -e "Имя сервера репозитория: $repo_name"
echo -e "Прокол репозитория: $repo_proto"
####################################################################
#                                                                  #
#    Репозитории                                                   #
#                                                                  #
####################################################################
if $set_repo ; then
    echo 'set_repo - true'
# sources.list
    sed -i 's/^deb/#deb/g' /etc/apt/sources.list
    sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list
    sed -i 's/ftp:\/\//https:\/\//g' /etc/apt/sources.list
    sed -i 's/download.astralinux/dl.astralinux/g' /etc/apt/sources.list
    echo -e "#deb https://dl.astralinux.ru/astra/frozen/1.7_x86-64/1.7.3/repository-base 1.7_x86-64 main non-free contrib" | tee -a /etc/apt/sources.list > /dev/null
    echo -e "#deb https://dl.astralinux.ru/astra/frozen/1.7_x86-64/1.7.3/repository-extended 1.7_x86-64 main contrib non-free" | tee -a /etc/apt/sources.list >/dev/null
    sort -u /etc/apt/sources.list -o /etc/apt/sources.list
    sed -i "s/deb https:\/\/dl.astralinux.ru/deb $repo_proto:\/\/$repo_name/g" /etc/apt/sources.list
    sed -i "/$repo_proto:\/\/$repo_name\/astra\/frozen\/1.7_x86-64\/1.7.3\/repository-base/s/^#\+//" /etc/apt/sources.list # убираем комент в строке по найденому слову
    sed -i "/$repo_proto:\/\/$repo_name\/astra\/frozen\/1.7_x86-64\/1.7.3\/repository-extended/s/^#\+//" /etc/apt/sources.list # убираем комент в строке по найденому слову
    echo -e "\nРепозитории astra обновлены"
# sources.list.d
    find /etc/apt/sources.list.d/ -type f -exec sed -i 's/^deb/#deb/g' {} \;
    find /etc/apt/sources.list.d/ -type f -exec sed -i 's/http:\/\//https:\/\//g' {} \;
    find /etc/apt/sources.list.d/ -type f -exec sed -i 's/ftp:\/\//https:\/\//g' {} \;
    find /etc/apt/sources.list.d/ -type f -exec sed -i 's/download.astralinux/dl.astralinux/g' {} \;
    echo -e "#deb https://dl.astralinux.ru/aldpro/stable/repository-main/ 1.4.1 main" | sudo tee -a /etc/apt/sources.list.d/aldpro.list >/dev/null
    echo -e "#deb https://dl.astralinux.ru/aldpro/stable/repository-extended/ generic main" | sudo tee -a /etc/apt/sources.list.d/aldpro.list >/dev/null
    find /etc/apt/sources.list.d/ -type f -exec sort -u {} -o {} \;
    find /etc/apt/sources.list.d/ -type f -exec sed -i "s/deb https:\/\/dl.astralinux.ru/deb $repo_proto:\/\/$repo_name/g" {} \;
    sed -i "/$repo_proto:\/\/$repo_name\/aldpro\/stable\/repository-main\/ 1.4.1/s/^#\+//" /etc/apt/sources.list.d/aldpro.list # убираем комент в строке по найденому слову
    sed -i "/$repo_proto:\/\/$repo_name\/aldpro\/stable\/repository-extended\/ generic/s/^#\+//" /etc/apt/sources.list.d/aldpro.list # убираем комент в строке по найденому слову
    echo -e "\nРепозитории ald обновлены"
echo -e "\nРепозитории обновлены"
else
    echo 'set_repo - false'
fi
